version: '3.5'
services:
  rr-net-back-postgres-dev:
    image: postgres:12.1
    container_name: rr-net-back-postgres-dev
    restart: on-failure
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    volumes:
      - './volume-posgtres:/var/lib/postgresql/data'
