version: '3.5'

networks:
  app-network:
    driver: bridge
    
services:
  rr-net-back-postgres:
    image: postgres:12.1
    container_name: rr-net-back-postgres
    restart: on-failure
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    volumes:
      - './volume-posgtres:/var/lib/postgresql/data'
    networks:
      - app-network

  rr-net-back-api:
    container_name: rr-net-back-api
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - rr-net-back-postgres
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000/
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_EXTERNAL_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    
